/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndk_file_encrpty_Cryptor */

#ifndef _Included_com_example_ndk_file_encrpty_Cryptor
#define _Included_com_example_ndk_file_encrpty_Cryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_file_encrpty_Cryptor
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1file_1encrpty_Cryptor_encrypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_ndk_file_encrpty_Cryptor
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_1file_1encrpty_Cryptor_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
